[project]
name = "doc-convert-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "markitdown>=0.0.1a2",
    "pip>=24.3.1",
]
